# Buidling the first model

In [93]:
# imports
from dataclasses import dataclass
from typing import Any


import pandas as pd
import numpy as np

from sklearn.preprocessing import Normalizer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.model_selection import train_test_split

# scikit learn later
%matplotlib inline

# Load dataset

In [8]:
# load dataset
dataset_1 = "../data/input_dataset-1.parquet"
dataset_2 = "../data/input_dataset-2.parquet"
bolt_pretension_file = "../data/bolt_pretension.csv"
prediction_input_file = "../data/prediction_input.parquet"

In [9]:
validation = pd.read_parquet(prediction_input_file)
validation.head()

,Unit_4_Power,Unit_4_Reactive Power,Turbine_Guide Vane Opening,Turbine_Pressure Drafttube,Turbine_Pressure Spiral Casing,Turbine_Rotational Speed,mode
timepoints,,,,,,,
1971-01-25 11:06:49,308.867868,5.592261,94.442351,158.159044,5279.876581,108.057467,operation
1971-01-25 11:06:50,308.898237,6.251969,94.445687,158.202829,5279.930843,108.057460,operation
1971-01-25 11:06:51,308.928605,7.037091,94.449024,158.246614,5279.985105,108.057454,operation
1971-01-25 11:06:52,308.958974,7.822213,94.452361,158.290399,5280.039368,108.057448,operation
1971-01-25 11:06:53,308.989343,8.607335,94.455698,158.302931,5280.058748,108.057442,operation

In [10]:
features = list(validation.columns)
features

['Unit_4_Power',
 'Unit_4_Reactive Power',
 'Turbine_Guide Vane Opening',
 'Turbine_Pressure Drafttube',
 'Turbine_Pressure Spiral Casing',
 'Turbine_Rotational Speed',
 'mode']

In [26]:
train_main = pd.read_parquet(dataset_2)
train_main.head()

,Unit_4_Power,Unit_4_Reactive Power,Turbine_Guide Vane Opening,Turbine_Pressure Drafttube,Turbine_Pressure Spiral Casing,Turbine_Rotational Speed,mode,Bolt_1_Steel tmp,Bolt_1_Tensile,Bolt_2_Tensile,...,Bolt_5_Tensile,Bolt_6_Tensile,Bolt_1_Torsion,Bolt_2_Torsion,Bolt_3_Torsion,Bolt_4_Torsion,Bolt_5_Torsion,Bolt_6_Torsion,lower_bearing_vib_vrt,turbine_bearing_vib_vrt
timepoints,,,,,,,,,,,,,,,,,,,,,
1970-12-19 09:51:44,262.204308,2.899036,82.279976,173.955216,5310.799181,107.964278,operation,4.133996,1598.481390,1480.989917,...,1635.585700,1674.848803,175.758460,163.956613,146.288741,225.535170,297.780208,161.148100,NaN,NaN
1970-12-19 09:51:45,262.104319,3.344630,82.277248,173.989815,5311.219755,107.964273,operation,4.134078,1598.477449,1480.989528,...,1635.588478,1674.823883,175.755164,163.951680,146.284164,225.527142,297.771627,161.145094,NaN,NaN
1970-12-19 09:51:46,262.004330,3.790223,82.274520,174.024413,5311.640329,107.964269,operation,4.134731,1598.479316,1481.003188,...,1635.583464,1674.841318,175.764601,163.952007,146.283423,225.522291,297.777115,161.144487,NaN,NaN
1970-12-19 09:51:47,261.904340,4.235817,82.271792,174.059012,5312.060902,107.964264,operation,4.134270,1598.490184,1481.028827,...,1635.581384,1674.843245,175.763157,163.953924,146.283633,225.535827,297.772578,161.144037,NaN,NaN
1970-12-19 09:51:48,261.804351,4.064759,82.269064,174.153819,5312.405938,107.964259,operation,4.133583,1598.494073,1481.059017,...,1635.591746,1674.872300,175.760959,163.951968,146.286946,225.534231,297.774191,161.151967,NaN,NaN

In [27]:
train_main_features = train_main[features]
train_main_features.head()

,Unit_4_Power,Unit_4_Reactive Power,Turbine_Guide Vane Opening,Turbine_Pressure Drafttube,Turbine_Pressure Spiral Casing,Turbine_Rotational Speed,mode
timepoints,,,,,,,
1970-12-19 09:51:44,262.204308,2.899036,82.279976,173.955216,5310.799181,107.964278,operation
1970-12-19 09:51:45,262.104319,3.344630,82.277248,173.989815,5311.219755,107.964273,operation
1970-12-19 09:51:46,262.004330,3.790223,82.274520,174.024413,5311.640329,107.964269,operation
1970-12-19 09:51:47,261.904340,4.235817,82.271792,174.059012,5312.060902,107.964264,operation
1970-12-19 09:51:48,261.804351,4.064759,82.269064,174.153819,5312.405938,107.964259,operation

In [58]:


target_vars = ["Bolt_1_Tensile", "Bolt_2_Tensile", "Bolt_3_Tensile", "Bolt_4_Tensile", "Bolt_5_Tensile", "Bolt_6_Tensile"]
targets_df = train_main[target_vars]
targets_df

,Bolt_1_Tensile,Bolt_2_Tensile,Bolt_3_Tensile,Bolt_4_Tensile,Bolt_5_Tensile,Bolt_6_Tensile
timepoints,,,,,,
1970-12-19 09:51:44,1598.481390,1480.989917,1684.247079,1601.359944,1635.585700,1674.848803
1970-12-19 09:51:45,1598.477449,1480.989528,1684.261611,1601.366508,1635.588478,1674.823883
1970-12-19 09:51:46,1598.479316,1481.003188,1684.270504,1601.374254,1635.583464,1674.841318
1970-12-19 09:51:47,1598.490184,1481.028827,1684.270683,1601.383179,1635.581384,1674.843245
1970-12-19 09:51:48,1598.494073,1481.059017,1684.271062,1601.378391,1635.591746,1674.872300
...,...,...,...,...,...,...
1971-01-25 11:06:44,1637.386115,1504.557822,1701.651420,1606.276545,1640.704071,1690.014705
1971-01-25 11:06:45,1637.365865,1504.546091,1701.654301,1606.271877,1640.711250,1690.017029
1971-01-25 11:06:46,1637.384133,1504.538696,1701.656143,1606.250028,1640.699142,1690.002008
1971-01-25 11:06:47,1637.357141,1504.531582,1701.662201,1606.245665,1640.685782,1689.995135
1971-01-25 11:06:48,1637.344985,1504.525065,1701.658131,1606.286286,1640.698392,1690.004759

In [ ]:
for target_var in target_vars:
    targets[target_var] = train_main[target_var]
targets

# Preprocessing and feature engineering

In [29]:
def copy_df(df:pd.DataFrame):
    return df.copy()

In [30]:
def mode_to_numerical(df: pd.DataFrame):
    df.loc[:, "mode"] = (df["mode"]=="operation").astype(float)
    return df

In [40]:
def drop_na(df: pd.DataFrame):
    return df.dropna(axis=0)

In [41]:
train_main_features_prep = (
    train_main_features.pipe(copy_df)
    .pipe(mode_to_numerical)
    .pipe(drop_na)
)
train_main_features_prep.head()

,Unit_4_Power,Unit_4_Reactive Power,Turbine_Guide Vane Opening,Turbine_Pressure Drafttube,Turbine_Pressure Spiral Casing,Turbine_Rotational Speed,mode
timepoints,,,,,,,
1970-12-19 09:51:44,262.204308,2.899036,82.279976,173.955216,5310.799181,107.964278,1.0
1970-12-19 09:51:45,262.104319,3.344630,82.277248,173.989815,5311.219755,107.964273,1.0
1970-12-19 09:51:46,262.004330,3.790223,82.274520,174.024413,5311.640329,107.964269,1.0
1970-12-19 09:51:47,261.904340,4.235817,82.271792,174.059012,5312.060902,107.964264,1.0
1970-12-19 09:51:48,261.804351,4.064759,82.269064,174.153819,5312.405938,107.964259,1.0

In [70]:
validation_prep = (
    validation.pipe(copy_df)
    .pipe(mode_to_numerical)
    .pipe(drop_na)
)
validation_prep.head()

,Unit_4_Power,Unit_4_Reactive Power,Turbine_Guide Vane Opening,Turbine_Pressure Drafttube,Turbine_Pressure Spiral Casing,Turbine_Rotational Speed,mode
timepoints,,,,,,,
1971-01-25 11:06:49,308.867868,5.592261,94.442351,158.159044,5279.876581,108.057467,1.0
1971-01-25 11:06:50,308.898237,6.251969,94.445687,158.202829,5279.930843,108.057460,1.0
1971-01-25 11:06:51,308.928605,7.037091,94.449024,158.246614,5279.985105,108.057454,1.0
1971-01-25 11:06:52,308.958974,7.822213,94.452361,158.290399,5280.039368,108.057448,1.0
1971-01-25 11:06:53,308.989343,8.607335,94.455698,158.302931,5280.058748,108.057442,1.0

In [71]:
print(validation.shape)
print(validation_prep.shape)

(226364, 7)
(226364, 7)

## Normalize data

## Training data

In [43]:
normalizer = Normalizer().fit(train_main_features_prep)

train_main_features_prep_norm = normalizer.transform(train_main_features_prep)
train_main_features_prep_norm

array([[4.92694364e-02, 5.44742731e-04, 1.54607987e-02, ...,
        9.97924422e-01, 2.02870013e-02, 1.87904755e-04],
       [4.92467972e-02, 6.28422725e-04, 1.54590774e-02, ...,
        9.97925420e-01, 2.02854142e-02, 1.87890064e-04],
       [4.92241612e-02, 7.12089629e-04, 1.54573562e-02, ...,
        9.97926410e-01, 2.02838273e-02, 1.87875373e-04],
       ...,
       [5.83294909e-02, 8.44958962e-04, 1.78387462e-02, ...,
        9.97482298e-01, 2.04126052e-02, 1.88905054e-04],
       [5.83384489e-02, 9.14841515e-04, 1.78403617e-02, ...,
        9.97481345e-01, 2.04137312e-02, 1.88915485e-04],
       [5.83463953e-02, 9.84714695e-04, 1.78416677e-02, ...,
        9.97480480e-01, 2.04145030e-02, 1.88922639e-04]])

### validation data

In [72]:
validation_prep_norm = normalizer.transform(validation_prep)

## Preprocess targets:

In [59]:
# drop nas
def drop_target_nans(targets_df, train_raw_df):
    is_nan_row = train_raw_df.isna().any(axis=1)
    targets_df = targets_df[~is_nan_row]
    return targets_df

In [62]:
targets_df_prep = (
    targets_df.pipe(copy_df)
    .pipe(drop_target_nans,train_main_features )
)
targets_df_prep.head()

,Bolt_1_Tensile,Bolt_2_Tensile,Bolt_3_Tensile,Bolt_4_Tensile,Bolt_5_Tensile,Bolt_6_Tensile
timepoints,,,,,,
1970-12-19 09:51:44,1598.481390,1480.989917,1684.247079,1601.359944,1635.585700,1674.848803
1970-12-19 09:51:45,1598.477449,1480.989528,1684.261611,1601.366508,1635.588478,1674.823883
1970-12-19 09:51:46,1598.479316,1481.003188,1684.270504,1601.374254,1635.583464,1674.841318
1970-12-19 09:51:47,1598.490184,1481.028827,1684.270683,1601.383179,1635.581384,1674.843245
1970-12-19 09:51:48,1598.494073,1481.059017,1684.271062,1601.378391,1635.591746,1674.872300

## Varify that data has the same shaep

In [63]:
targets_df_prep.shape

(1750000, 6)

In [64]:
train_main_features_prep_norm.shape

(1750000, 7)

# build model

In [90]:
@dataclass
class ModelResponse:
    model: Any
    train_mape: float
    test_mape: float

In [91]:
def train_bolts_models(train_df, targets_df, model_name="linear"):
    if model_name == "linear":
        model = LinearRegression
    else:
        raise ValueError()
    
    res = {}
    for target_name, target_data in targets_df.iteritems():
        X_train, X_test, y_train, y_test = train_test_split(train_df, target_data, test_size = 0.8, shuffle=True)
        m = model()
        m.fit(X_train, y_train)
        y_pred_train = m.predict(X_train)
        y_pred_test = m.predict(X_test)
        train_mape = mean_absolute_percentage_error(y_train, y_pred_train)
        test_mape = mean_absolute_percentage_error(y_test, y_pred_test)
        res[target_name] = ModelResponse(model = m, train_mape=train_mape, test_mape=test_mape)
        
    return res

In [92]:
model_responses = train_bolts_models(train_main_features_prep_norm, targets_df_prep)
model_responses

{'Bolt_1_Tensile': ModelResponse(model=LinearRegression(), train_mape=0.00525666329293947, test_mape=0.00526051988344541),
 'Bolt_2_Tensile': ModelResponse(model=LinearRegression(), train_mape=0.0034796956269112296, test_mape=0.003477725514092193),
 'Bolt_3_Tensile': ModelResponse(model=LinearRegression(), train_mape=0.0023387389846527763, test_mape=0.002339082240465969),
 'Bolt_4_Tensile': ModelResponse(model=LinearRegression(), train_mape=0.0005248758161231838, test_mape=0.0005241996228216521),
 'Bolt_5_Tensile': ModelResponse(model=LinearRegression(), train_mape=0.0003949348346790005, test_mape=0.00039477406940436244),
 'Bolt_6_Tensile': ModelResponse(model=LinearRegression(), train_mape=0.001873406657294429, test_mape=0.001874629391085241)}